Game.Localization = {
    en: {
        PLAY_BTN: 'PLAY',
        MORE_GAMES_BTN: 'More Games',
        SETTINGS_TITLE_IMG: 'SETTINGS',
        CLOSE_BTN: 'Close',
        PAUSE_TITLE_IMG: 'GAME PAUSED',
        RETRY_BTN: 'Retry level',
        EXIT_BTN: 'Quit level',
        NEXT_BTN: 'Next',
        CONTINUE_BTN: 'Continue',
        EXIT_LABEL: 'Are you sure\nyou want to quit\nthe current level?\n\nYou will lose \nyour current score.',
        YES_BTN: 'Yes',
        NO_BTN: 'No',
        LEVEL_LABEL: 'LEVEL',
        LEVEL_END_IMG: 'LEVEL COMPLETED!',
        FACEBOOK_IMG: 'Like us on Facebook',
        FB_1_IIMG: 'Almost done!',
        FB_2_IMG: 'Confirm your like by clicking the like button below.',
        FB_3_IMG: 'Thanks for your support! It really helps!',
        TUTORIAL1_1: "Your kids have been frozen! \nUnfreeze them by melting \nthe ice with your fire breath.",
        TUTORIAL1_2: "Guide your fire: \nDrag the green blocks within\nthe boundaries of the pins.",
        TUTORIAL1_3: "Try to collect \nall stars",
        TUTORIAL3_1: "Blue blocks cannot be moved",
        TUTORIAL4_1: "You can rotate purple blocks \nby clicking on them. \n\nBeware: they cannot be moved.",
        TUTORIAL5_1: "Some stars disappear after \na certain amount of moves",
        TUTORIAL5_2: "Colors indicate \nwhich stars disappear sooner",
        TUTORIAL6_1: "Tip: \nmoving multiple blocks \nat once counts as \none move.",
        TUTORIAL6_2: "This is needed to \nreach certain stars \nin time!",
        TUTORIAL7_1: "These mechanic blocks \ncannot be moved. \nThey move automatically \nwhen given the space.",
        TUTORIAL7_2: "The arrows indicate \nwhich direction they move",
        FINISHED_GAME: "Congratulations!!\nYou have completed this\n episode of\nHoney, they froze our kids.\nHope to see you soon in:\nHoney, they froze our kids 2!"
    },
    nl: {
        PLAY_BTN: 'SPEEL',
        MORE_GAMES_BTN: 'Meer Spellen',
        SETTINGS_TITLE_IMG: 'Instellingen',
        CLOSE_BTN: 'Sluiten',
        PAUSE_TITLE_IMG: 'PAUZE',
        RETRY_BTN: 'Level Herstarten',
        EXIT_BTN: 'Verlaat Level',
        NEXT_BTN: 'Volgende',
        CONTINUE_BTN: 'Doorgaan',
        EXIT_LABEL: 'Weet je zeker dat\nje het level wilt\nverlaten?\n\nJe verliest dan de \nhuidige score.',
        YES_BTN: 'Ja',
        NO_BTN: 'Nee',
        MOVES_LABEL: 'ZETTEN',
        LEVEL_LABEL: 'LEVEL',
        LEVEL_END_IMG: 'LEVEL VOLTOOID!',
        FACEBOOK_IMG: 'Like us on Facebook',
        TUTORIAL1_1: "Je kinderen zijn bevroren! \nOntdooi het ijs waarin ze \ngevangen zitten door \nvuur te spuwen. ",
        TUTORIAL1_2: "Begeleid je vuur:\nVersleep de groene blokken\nbinnen de omheining \nvan pinnen. ",
        TUTORIAL1_3: "Probeer zo veel mogelijk \nsterren te verzamelen.",
        TUTORIAL3_1: "Blauwe blokken kan je\nniet verplaatsen. ",
        TUTORIAL4_1: "Paarse blokken kan je \ndraaien door er op te klikken.\nLet wel op: \nje kunt ze niet verplaatsen.",
        TUTORIAL5_1: "Sommige sterren verdwijnen\nna een bepaald aantal zetten.",
        TUTORIAL5_2: "Kleuren laten zien \nwelke ster eerder verdwijnt.",
        TUTORIAL6_1: "Tip: als je meerdere \nblokken tegelijk beweegt \ntelt dit maar als één beweging.",
        TUTORIAL6_2: "Dit is nodig om \nbij sommige sterren \nte komen!",
        TUTORIAL7_1: "Mechanische blokken\nkunnen niet \nverplaatst worden.\nZe bewegen automatisch als \nze de ruimte krijgen.",
        TUTORIAL7_2: "Pijlen laten zien \nwaar het blok naartoe \nbeweegt.",
        FINISHED_GAME: "Gefeliciteerd!! Je hebt\n deze aflevering van\n'Honey, they froze our kids' \nuitgespeeld. We hopen je \nsnel terug te zien in:\nHoney, they froze our kids 2!"
    },
    de: {
        PLAY_BTN: 'SPIEL',
        MORE_GAMES_BTN: 'Mehr Spiele',
        SETTINGS_TITLE_IMG: 'EINSTELLUNGEN',
        CLOSE_BTN: 'Schließen',
        PAUSE_TITLE_IMG: 'SPIEL PAUSE',
        RETRY_BTN: 'Neu Start Level',
        EXIT_BTN: 'Verlasse Level',
        NEXT_BTN: 'Nächster',
        CONTINUE_BTN: 'Fortfahren',
        EXIT_LABEL: 'Bist du sicher \ndu willst das akutelle \nLevel beenden?\n\nDu wirst deine \n Punkte verlieren.',
        YES_BTN: 'Ja',
        NO_BTN: 'Nein',
        MOVES_LABEL: 'SETZEN',
        LEVEL_LABEL: 'LEVEL',
        LEVEL_END_IMG: 'LEVEL ABGESCHLOSSEN!',
        FACEBOOK_IMG: 'Like us on Facebook',
        TUTORIAL1_1: "Deine Kinder wurden gefroren! \nTaue sie auf indem du sie mit \ndeinem Feueratem anhauchst.",
        TUTORIAL1_2: "Lenke dein Feuer: \nZiehe die grünen \nBlöcke innerhalb der \nGrenze der Pins.",
        TUTORIAL1_3: "Versuche alle Sterne \nzu sammeln",
        TUTORIAL3_1: "Blaue Blöcke können \nnicht bewegt werden",
        TUTORIAL4_1: "Du kannst die lila Blöcke \nrotieren indem \ndu auf sie klickst.\nBeachte: sie können \nnicht bewegt werden.",
        TUTORIAL5_1: "Manche Sterne verschwinden \nnach einer bestimmten \nAnzahl an Zügen",
        TUTORIAL5_2: "Farben zeigen an \nwelche Sterne früher \nverschwinden",
        TUTORIAL6_1: "Tip: \nverschiedene Blöcke \ngleichzeitig bewegen, \ngilt was als ein Zug.",
        TUTORIAL6_2: "Dies ist nötig \num bestimmte Sterne \nrechtzeitig zu erreichen!",
        TUTORIAL7_1: "Diese mechanischen Blöcke \nkönnen nicht bewegt werden. \nSie bewegen sich automatisch \nwenn sie Platz haben.",
        TUTORIAL7_2: "Der Pfeil zeigt \nin welche Richtung \nsie sich bewegen",
        TUTORIAL8_1: "In der Klemme? Drücke auf den Neu Versuch Knopf um das Level neu zu versuchen.",
        FINISHED_GAME: "Glückwunsch!! Du hast \nHoney, they froze our kids. \nabgeschlossen! Wir hoffen \ndich wieder in Honey, they \nfroze our kids 2 zu sehen!"
    },
    es: {
        PLAY_BTN: 'JUGAR',
        MORE_GAMES_BTN: 'Más Juegos',
        SETTINGS_TITLE_IMG: 'OPCIONES',
        CLOSE_BTN: 'Cerrar',
        PAUSE_TITLE_IMG: 'PAUSA',
        RETRY_BTN: 'Reiniciar Nivel',
        EXIT_BTN: 'Salir del nivel',
        CONTINUE_BTN: 'Continuar',
        NEXT_BTN: 'Siguiente',
        EXIT_LABEL: '¿Estás seguro\nde que quieres\ndejar este nivel?\n\nPederás tu \npuntuación actual.',
        YES_BTN: 'Sí',
        NO_BTN: 'No',
        MOVES_LABEL: 'MOVIMIENTOS',
        LEVEL_LABEL: 'NIVEL',
        LEVEL_END_IMG: '¡NIVEL COMPLETADO!',
        FACEBOOK_IMG: 'Like us on Facebook',
        TUTORIAL1_1: "¡Tus pequeños han sido \ncongelados! Descongelalos \nfundiendo tel hielo \ncon tu aliento de fuego.",
        TUTORIAL1_2: "Guía el fuego: \nArrastra los bloques verdes\ndentro de los límites \nde los pins.",
        TUTORIAL1_3: "Intenta recolectar \ntodas las estrellas",
        TUTORIAL3_1: "Los bloques azules \nno pueden moverse.",
        TUTORIAL4_1: "Puedes girar los bloques \nmorados pulsando \nsobre ellos. \nAtención: \nno se pueden desplazar.",
        TUTORIAL5_1: "Algunas estrellas desaparecen \ndespués de cierto \nnúmero de movimientos",
        TUTORIAL5_2: "Los colores indican \nqué estrellas \ndesaparecerán antes.",
        TUTORIAL6_1: "Consejo: \nMover varios bloques \na la vez cuenta como \nun solo movimiento.",
        TUTORIAL6_2: "¡Es necesario hacerlo \npara coger todas las \nestrellas a tiempo!",
        TUTORIAL7_1: "Estos bloques mecánicos \nno pueden moverse. \nSe mueven automáticamente \ncuando disponen de espacio.",
        TUTORIAL7_2: "Las flechas indican \nen qué dirección se moverán.",
        TUTORIAL8_1: "¿Atascado? Pulsa el botón de reintentar par empezar de nuevo.",
        FINISHED_GAME: "¡¡Felicidades!! Has \ncompletado este episodio de\nHoney, they froze our kids!\n¡Esperamos verte pronto en\n Honey, they froze our kids 2!"
    },
    fr: {
        PLAY_BTN: 'JOUER',
        MORE_GAMES_BTN: 'Plus de jeux',
        SETTINGS_TITLE_IMG: 'PARAMETRES',
        CLOSE_BTN: 'Fermer',
        PAUSE_TITLE_IMG: 'JUE EN PAUSE',
        RETRY_BTN: 'Re-tenter',
        EXIT_BTN: 'Quitter niveau',
        NEXT_BTN: 'Suivant',
        CONTINUE_BTN: 'Continuer',
        EXIT_LABEL: 'Es-tu sûr\nde vouloir quitter\nce niveau ?\n\nTu perdras\ntes points.',
        YES_BTN: 'Oui',
        NO_BTN: 'Non',
        MOVES_LABEL: 'TOURS',
        LEVEL_LABEL: 'NIVEAU',
        LEVEL_END_IMG: 'NIVEAU REUSSI!',
        FACEBOOK_IMG: 'Like us on Facebook',
        TUTORIAL1_1: "Tes enfants sont gelés !\nLibère-les en faisant\nfondre la glace avec\nton souffle de feu.",
        TUTORIAL1_2: "Guide tes flammes :\ndéplace les blocs verts\nà l'intérieur des limites.",
        TUTORIAL1_3: "Essaie d'avoir\ntoutes les étoiles.",
        TUTORIAL3_1: "Tu ne peux pas déplacer\nles blocs bleus.",
        TUTORIAL4_1: "Tourne les blocs violet\nen cliquant dessus.\nAttention : tu ne peux\npas les déplacer.",
        TUTORIAL5_1: "Certaines étoiles\ndisparaissent après\nplusieurs mouvements.",
        TUTORIAL5_2: "Les couleurs indiquent\nquelles étoiles\ndisparaîtront bientôt.",
        TUTORIAL6_1: "Astuce :\ndéplacer plusieurs blocs\nd'un coup compte pour\nun seul mouvement.",
        TUTORIAL6_2: "C'est nécessaire\npour atteindre certaines\n étoiles à temps !",
        TUTORIAL7_1: "Tu ne peux pas déplacer\nles blocs automatiques.\nIls le font tout seul quand\ntu leur fais de la place.",
        TUTORIAL7_2: "Les flèches indiquent\ndans quelle direction\vils \nse déplacent.",
        TUTORIAL8_1: "Coincé ?\nUtilise le bouton\nRe-tenter pour\nrecommencer le niveau.",
        FINISHED_GAME: "Fellicitations!! Tu as \nréussi cet épisode def\nHoney, they froze our kids!\nA bientôtt pour\n Honey, they froze our kids 2!"
    },
    it: {
        PLAY_BTN: 'GIOCA',
        MORE_GAMES_BTN: 'Altri Giochi',
        SETTINGS_TITLE_IMG: 'SETTING',
        CLOSE_BTN: 'Chiudi',
        PAUSE_TITLE_IMG: 'IN PAUSA',
        RETRY_BTN: 'Riprova',
        EXIT_BTN: 'Lascia livello',
        NEXT_BTN: 'Il Prossimo',
        CONTINUE_BTN: 'Continua',
        EXIT_LABEL: 'Sicuro di\nvoler lasciare\nil livello?\n\nPerderai\ni punti.',
        YES_BTN: 'Si',
        NO_BTN: 'No',
        MOVES_LABEL: 'MOSSE',
        LEVEL_LABEL: 'LIVELLO',
        LEVEL_END_IMG: 'LIVELLO COMPLETATO!',
        FACEBOOK_IMG: 'Like us on Facebook',
        TUTORIAL1_1: "I tuoi ragazzi sono congelati! \nscongela \nil ghiaccio sputando fuoco.",
        TUTORIAL1_2: "Guida il fuoco: \ntrascina i quadrati verdi \ndentro i confini degli spilli.",
        TUTORIAL1_3: "Cerca di collezionare \ntutte le stelle",
        TUTORIAL3_1: "I blocchi blu non possono \nessere spostati",
        TUTORIAL4_1: "Puoi ruotare i blocchi viola \ncliccandoci sopra. \nAttenzione: \nnon possono essere spostati.",
        TUTORIAL5_1: "Alcune stelle spariscono dopo \na un certo numero \ndi spostamenti",
        TUTORIAL5_2: "I colori indicano \nquali stelle spariranno prima",
        TUTORIAL6_1: "Consiglio: muovere più di \nun blocco in una volta \ncorrisponde ad un'unica \nmossa.",
        TUTORIAL6_2: "Questo è necessario \nper raggiungere certe \nstelle in tempo!",
        TUTORIAL7_1: "Questi blocchi meccanici \n non possono essere spostati. \nSi spostano automaticamente \nquando viene liberato spazio.",
        TUTORIAL7_2: "Le frecce indicano \nin quale direzione si spostano",
        TUTORIAL8_1: "bloccato? schiaccia il bottone riprova per ricominciare il livello e provare ancora.",
        FINISHED_GAME: "Congratulazioni!! Hai \ncompletato questo episodio di\nHoney, they froze our kids!\nCi rivediamo in \nHoney, they froze our kids 2!"
    },
    pt: {
        PLAY_BTN: 'JOGAR',
        MORE_GAMES_BTN: 'Mais Jogos',
        SETTINGS_TITLE_IMG: 'CONFIGURAÇÕES',
        CLOSE_BTN: 'Fechar',
        PAUSE_TITLE_IMG: 'JOGO PAUSADO',
        RETRY_BTN: 'Tentar nível',
        EXIT_BTN: 'Feche a fase',
        NEXT_BTN: 'Próximo ',
        CONTINUE_BTN: 'Continuar',
        EXIT_LABEL: 'Você tem certeza\nque quer fechar\ntessa fase?\n\nVocê perderá \na sua pontuação atual.',
        YES_BTN: 'Sim',
        NO_BTN: 'Não',
        MOVES_LABEL: 'JOGADAS',
        LEVEL_LABEL: 'NÍVEL',
        LEVEL_END_IMG: 'NÍVEL COMPLETADO!',
        FACEBOOK_IMG: 'Like us on Facebook',
        TUTORIAL1_1: "Seus filhos foram congelados! \nDescongele-os \ncom o seu bafo de fogo.",
        TUTORIAL1_2: "Guie o seu fogo: \nLeve os blocos verdes para\nas bordas dos pinos.",
        TUTORIAL1_3: "Tente pegar \ntodas as estrelas",
        TUTORIAL3_1: "Blocos azuis não são movidos",
        TUTORIAL4_1: "Você pode girar os blocos \nroxos clicando neles. Saiba: eles não podem \nser movidos.",
        TUTORIAL5_1: "Algumas estrelas desaparecem \ndepois de um certo números \nde movimentos",
        TUTORIAL5_2: "As cores indicam \nquais estrelas desaparecerão \nmais rápido",
        TUTORIAL6_1: "Dica: mover múltiplos \nblocos ao mesmo tempo \nconta como um movimento.",
        TUTORIAL6_2: "É preciso mover algumas \nestrelas a tempo!",
        TUTORIAL7_1: "Os blocos mecânicos não \npodem ser movidos. Eles \nse movem automaticamente \nquando têm espaço.",
        TUTORIAL7_2: "As setas indicam \nem qual direção eles se movem",
        TUTORIAL8_1: "Preso? Pressione o botão tentar novamente para recomeçar a fase e tente de novo.",
        FINISHED_GAME: "Parabéns!! Você \ncompletou esta fase de\nHoney, they froze our kids!\nEspero vê-lo/a em breve na \nHoney, they froze our kids 2!"
    },
    tr: {
        PLAY_BTN: 'OYNA',
        MORE_GAMES_BTN: 'Diğer oyunlar',
        SETTINGS_TITLE_IMG: 'Ayarlar',
        CLOSE_BTN: 'Kapat',
        PAUSE_TITLE_IMG: 'OYUN DURDU',
        RETRY_BTN: 'Tekrar dene',
        EXIT_BTN: 'Seviyeyi bırak',
        NEXT_BTN: 'Sonraki',
        CONTINUE_BTN: 'Devam et',
        EXIT_LABEL: 'Mevcut\nseviyeyi bırakmak\nistediğinden emin misin?\n\nMevcut puanını \nkaybedeceksin.',
        YES_BTN: 'Evet',
        NO_BTN: 'Hayır',
        MOVES_LABEL: 'Hamleler',
        LEVEL_LABEL: 'SEVIYE',
        LEVEL_END_IMG: 'SEVİYE TAMAMLANDI!',
        TUTORIAL1_1: "Çocukların donduruldu! \nAteşli nefesinle buzu eriterek \nçocukları çöz.",
        TUTORIAL1_2: "Ateşini yönlendir: \nYeşil blokları \niğnelerle sınırlı alana çek.",
        TUTORIAL1_3: "Bütün yıldızları \ntoplamaya çalış",
        TUTORIAL3_1: "Mavi bloklar oynatılamaz",
        TUTORIAL4_1: "Üstlerine tıklayarak mor \nblokları oynatabilirsin. \n\nDikkat: oynatılamazlar.",
        TUTORIAL5_1: "Bazı yıldızlar belirli sayıda\nhamleden sonra yok olur",
        TUTORIAL5_2: "Renkler hangi \nyıldızların önce yok \nolacaklarını gösterir",
        TUTORIAL6_1: "Tüyo: aynı anda birçok bloku \noynatmak tek hamle sayılır.",
        TUTORIAL6_2: "Bu, zamanında belirli \nyıldızlara ulaşmak \niçin gereklidir!",
        TUTORIAL7_1: "Bu mekanik bloklar \noynatılamıyor. \nYer verildiğinde otomatik\nolarak hareket ederler.",
        TUTORIAL7_2: "Oklar hangi yöne \nhareket ettiklerini gösterir",
        TUTORIAL8_1: "takıldı mı? seviyeyi tekrar başlatmak ve yeniden denemek için tekrar tuşuna bas.",
        FINISHED_GAME: "Tebrikler!!\nHoney, they froze our kids!\n'nin bu bölümünü bitirdin!\nHoney, the froze our kids 2!\n'de görüşmek üzere!"
    },
};